apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: track1-sandbox
spec:
  hard:
    pods: "500"
    requests.cpu: "500"
    requests.memory: "256Gi"
    limits.cpu: "500"
    limits.memory: "256Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-defaults
  namespace: track1-sandbox
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "1"
        memory: "512Mi"
      default:
        cpu: "1"
        memory: "512Mi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-namespace-default-deny
  namespace: track1-sandbox
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
